### ISSUE TITLE
Players occasionally can became transparent (as result of detecting "crash")

### ISSUE THREAD

**Issue by shockpast** [noaccessl/gmod-PhysicsCrashGuard#1]
[Screenshot](https://i.imgur.com/emEX04S.png) of how it looks in the game, it just happens absolutely randomly, even when players are staying still and don't anything (atleast on our server, where screenshot was taken)

I will try to look into this problem, by debugging and doing other messy stuff to make it detect crashes.

**Comment by AsuToki360** [comment]
It's still happening to me for no reason, although idk if this project is still alive.

**Comment by noaccessl** [comment]
> It's still happening to me for no reason, although idk if this project is still alive.

Fixed.
