### ISSUE TITLE
False positive triggering when unfreeze prop via physgun and the "R" key.

### ISSUE THREAD

**Issue by ghost** [noaccessl/gmod-PhysicsCrashGuard#2]
Actually, subject, any attempt to unfreeze prop via physgun and the "R" key leads to a false positive triggering and the prop in this case becomes a ghost.
Triggers both when unfreezing one prop via crosshair targeting, and when unfreezing all props.
Conflicts between addons are excluded, because I also checked in the case of installing only your addon.

**Comment by noaccessl** [comment]
Fixed.
